### ISSUE TITLE
General questions ( no issue only for personal failues )

### ISSUE THREAD

**Issue by jedugsem** [arch-beryllium/build#2] opened 2021-01-24 17:00 UTC
Hallo,
sry is there a other way to reach you, maybe i' ll have some more questions. I've finally cloned the mirror but i have to build the kernel package for the beryllium-panel-ebbg branch so i changed the things in the PKGBUILD so how do you (cross) comile it with postmarketos i used envkernel.sh (dont think its working here)

**Comment by provokateurin** [comment] 2021-01-24 17:45
Do you have matrix? That would be the easiest way I think.
I'm building all packages with https://github.com/arch-beryllium/repo-builder in a aarch64 rootfs.
I think I can create a setup to cross-compile (not using qemu) packages so that you can use that.
The general problem with cross-compiling are the dependencies (especially libraries), but the kernel should be easy.
I can give no ETA, but a few days at least.

**Comment by jedugsem** [comment] 2021-01-24 19:35
i got a error which doesn't brake the building process: 
(145/145) upgrading xfsprogs                       [#################] 100%
New optional dependencies for xfsprogs
    python: for xfs_scrub_all script
    smtp-forwarder: for xfs_scrub_fail script
error: hook /usr/share/libalpm/hooks/40-update-ca-trust.hook line 5: invalid value Path

**Comment by provokateurin** [comment] 2021-01-24 19:48
Hm I've never seen that. Maybe it slipped past me

**Comment by jedugsem** [comment] 2021-01-24 22:08
i'll use ./qemu.sh to build but i cant resize the image

**Comment by provokateurin** [comment] 2021-01-24 22:09
qemu.sh just runs the image, but it can't resize yes. That's intended

**Comment by jedugsem** [comment] 2021-01-25 10:02
I know i resiesed i manually (qemu-img resize ... ) but the space available doesn't change, any idear or could you build the package for me i could send you the PKBUILD

**Comment by jedugsem** [comment] 2021-01-25 10:03
Thanks a lot for your work and time i feel a bit annoying

**Comment by provokateurin** [comment] 2021-01-25 10:11
Why do you need more space? I know there is not much available, but it's only for quick development. Do you want to build the kernel in the image?

**Comment by jedugsem** [comment] 2021-01-25 10:12
yes

**Comment by jedugsem** [comment] 2021-01-25 10:12
i dont have antother idear i'm trying about 3 hours becuase in chroot there some /dev devices missing

**Comment by provokateurin** [comment] 2021-01-25 10:13
Did you try rebooting? Some times when something with the mounts fails rebooting fixes it

**Comment by provokateurin** [comment] 2021-01-25 10:27
If you wait a little I'll push some changes so you can easily cross-compile the kernel package yourself

**Comment by jedugsem** [comment] 2021-01-25 10:36
(small side note i tried compiling it with manjaro-arm-tool there is some error that some git buffer isn't big enough while downloading kernel source hope it'll work with yours) Thanks a lot will try when you uploaded

**Comment by provokateurin** [comment] 2021-01-25 10:43
Added cross-compilation in https://github.com/arch-beryllium/build/commit/557fa4744a2699b3266fbd91888231ee09f8a2b2.
You can use the new instructions at the bottom of the readme, but you need to adjust the branch in the source URL in the PKGBUILD before building it.

**Comment by jedugsem** [comment] 2021-01-25 13:28
Thanks a lot i got everything to build, but i have a problem with plasma mobile it displays a blank kwin with cursor in the middle which is moveable (so kernel work because that contains the drivers for display and touch) but nothing else would try phosh later (how can i see when it resizes the rootfs or how was the command to see the output behind the bootsplash dmesg -w display only a few information)

**Comment by provokateurin** [comment] 2021-01-25 14:03
There was an issue lately where upgrading sddm resulted in a login issue. Seems like you just hit it. For me the latest mirrored packages and a fresh rootfs worked yesterday, but I can try again in a few hours and see if I also get the issue. In the mean time you should check that you have the latest packages mirrored.

**Comment by jedugsem** [comment] 2021-01-25 16:47
phosh never come out of the bootsplash after like 10 mins

**Comment by provokateurin** [comment] 2021-01-25 16:59
You can disable the bootsplash temporarily with `echo 0 >/sys/devices/platform/bootsplash.0/enabled` to see what is wrong. In reality you just need to use `journalctl -b`. If you can't find the issue please attach the full log as a file

**Comment by provokateurin** [comment] 2021-01-25 17:27
I'm not able to confirm your issue. Plasma Mobile and Phosh both work with the latest packages

**Comment by provokateurin** [comment] 2021-01-27 20:15
Any progress? Do you need help with anything?

**Comment by jedugsem** [comment] 2021-01-30 10:59
thanks for asking, trying today to get good logs, i disabled the resizerootfs and fsck hook and put 14000 in the imagesize i also disabled the bootsplash. I'm using plasma-mobile will see how it goes

**Comment by provokateurin** [comment] 2021-01-30 11:02
Ok :+1:

**Comment by jedugsem** [comment] 2021-01-30 12:04
bootscreen somehow wasn't been disabled ,echo 0 >"$DEST/sys/devices/platform/bootsplash.0/enabled" at the end of the build function doesnt works

**Comment by jedugsem** [comment] 2021-01-30 12:45
the right down corner backlight doesn't works and plasma leaves me without top bar and navigation button row so i cant use it correctly but expect for that it works

**Comment by provokateurin** [comment] 2021-01-30 12:54
Sounds like the shell isn't coming up properly. I wonder why it's working for me but not for you.

**Comment by provokateurin** [comment] 2021-01-30 12:55
> bootscreen somehow wasn't been disabled ,echo 0 >"$DEST/sys/devices/platform/bootsplash.0/enabled" at the end of the build function doesnt works

Yeah it's not suposed to work like that. `/sys` is only accessible when booted.

**Comment by jedugsem** [comment] 2021-01-30 13:03
ok, i'm trying between 8-12 this evening again think phosh is more stable on arch because of danctnix

**Comment by jedugsem** [comment] 2021-01-30 13:04
and got bootsplash disabled by removing file in mkinitcpio.conf

**Comment by provokateurin** [comment] 2021-01-30 13:05
Yeah either remove it or disable the symlink in the pre-script

**Comment by provokateurin** [comment] 2021-01-30 16:05
I maybe found an explanation for why some things are broken for you: The commit message of https://gitlab.com/sdm845-mainline/sdm845-linux/-/commit/ee0bf1162a76274d2ae2285ee935daaf0d12dc34 explains that you should use a different dts to boot. I guess you didn't adjust that in the PKGBUILD as I also forgot it? You will need to update https://github.com/arch-beryllium/linux-beryllium/blob/main/PKGBUILD#L96 to the proper file.

**Comment by jedugsem** [comment] 2021-01-30 20:48
I know thats why i builded it myself, otherwise touch and display wouldn't work at all i think i have to ask venji. Do you also notice that the fps on phosh feel much lower than on plasma, is that a phosh issue?

**Comment by jedugsem** [comment] 2021-01-30 20:50
I changed the branch in the PKGBUILD for git, and changed the dtb apended to Image.gz-dtb

**Comment by jedugsem** [comment] 2021-01-30 20:51
how long takes the resize os hook on 16 or 32 GB sd u1 card for you

**Comment by provokateurin** [comment] 2021-01-30 20:52
> I know thats why i builded it myself, otherwise touch and display wouldn't work at all i think i have to ask venji. Do you also notice that the fps on phosh feel much lower than on plasma, is that a phosh issue?

The fps drop is normal, because Gtk 3 is not hardware accelerated. Plasma mobile with Qt5 is, but even the software rendering was much smoother than Gtk 3's software rendering.

**Comment by jedugsem** [comment] 2021-01-30 20:52
ok this will change with gtk4 i think?

**Comment by provokateurin** [comment] 2021-01-30 20:54
Yeah, but I heard porting to Gtk 4 is pretty hard, because they removed some wayland layers that are required by phosh, so it will take a long time or never happen I guess.

**Comment by jedugsem** [comment] 2021-01-30 20:58
oh sad thanks

**Comment by jedugsem** [comment] 2021-01-30 21:21
How long does the resize hook take for you?

**Comment by provokateurin** [comment] 2021-01-30 21:23
Not long like 20-30 seconds I think

**Comment by jedugsem** [comment] 2021-02-01 12:13
everything works now also with resize hook. I dont even know what was missing, i'll would like to know how you whould handle the two needed kernel versions, should it be a flag or would the user be asked when launching ./build, would try to realalize it the way you want. Btw only thing not works is anbox will try to resaerch today.  Thanks a lot

**Comment by jedugsem** [comment] 2021-02-01 12:14
btw the corner backlight problem remains

**Comment by provokateurin** [comment] 2021-02-01 12:16
I was thinking about providing both kernels as packages and you will select the package when building.
The last time I tested Anbox on 5.9 it worked, but I think it didn't work for people on the PinePhone on 5.10 so maybe we have the same issue.
I also have a problem with the backlight where there are bright and less brighter spots on the bottom of the screen.

**Comment by provokateurin** [comment] 2021-02-01 12:33
Maybe it's also possible to use one package with both dtbs. Then on the device it could just detect which panel is connected and flash the appropriate boot.img. On the dev machine you'd do it manually.

**Comment by provokateurin** [comment] 2021-02-01 12:44
Btw there is a new commit (https://gitlab.com/sdm845-mainline/sdm845-linux/-/commit/0ac9fe954c6b186c10526787abad3add6ed43931). You should probably rebuild your kernel and maybe some things are fixed.

**Comment by jedugsem** [comment] 2021-02-01 12:45
you have the tianma version so it's should be a driver idependent problem

**Comment by jedugsem** [comment] 2021-02-01 12:46
can i rebuild only the bootimg?

**Comment by provokateurin** [comment] 2021-02-01 12:46
Yeah the backlight problem has only to do with qcom wled and nothing with either panel.

**Comment by jedugsem** [comment] 2021-02-01 12:47
the idear with both dtb in one package was thrown away by venji atm because of the complicated bootloader i think

**Comment by provokateurin** [comment] 2021-02-01 12:48
If you rebuild the kernel package you can extract the new boot.img from there

**Comment by provokateurin** [comment] 2021-02-01 12:48
It's easier with the package I'm using where you can simpely reinstall the package into the rootfs and get the boot.img from there.

**Comment by provokateurin** [comment] 2021-02-01 12:49
> the idear with both dtb in one package was thrown away by venji atm because of the complicated bootloader i think

It will still use two dtbs, but just choose which to use when booted

**Comment by provokateurin** [comment] 2021-02-01 12:51
I think I will try to create the new kernel package today, but it won't be easy, because I have to manually pick the commits.

**Comment by provokateurin** [comment] 2021-02-01 12:54
You probably want to rebuild the rootfs or edit the pacman.conf like this commit (if you are using PlaMo): https://github.com/arch-beryllium/build/commit/be9dc6b1463fb9e9bd269f0ece270c0966ffbd4a

**Comment by jedugsem** [comment] 2021-02-01 13:04
what is other in your PKGBUILD i only modified the branch and the dtb in your kernel package. Also I think although you dont get battery and ?audio? with eebg branch you should only need to chose the dtb there both.
[PKGBUILD.txt](https://github.com/arch-beryllium/build/files/5904071/PKGBUILD.txt)

**Comment by jedugsem** [comment] 2021-02-01 13:05
build.sh has a function  which only builds the bootimg could i use this function for a full kernel update or is it needed to replace the kernel package on the sd card also

**Comment by jedugsem** [comment] 2021-02-01 13:07
someone made a telegram group btw if you would like to join https://t.me/linuxpocof1 athough it not that tecnical

**Comment by jedugsem** [comment] 2021-02-01 13:07
someone made a telegram group btw if you would like to join https://t.me/linuxpocof1 athough it not that tecnical

**Comment by provokateurin** [comment] 2021-02-01 13:18
I'm also in a Matrix group for mainlining sdm845 in general: https://matrix.to/#/#mainline-sdm845:connolly.tech

**Comment by provokateurin** [comment] 2021-02-01 13:28
> build.sh has a function which only builds the bootimg could i use this function for a full kernel update or is it needed to replace the kernel package on the sd card also

The problem is it reinstalls the package I built so it wont work for you (yet).

**Comment by jedugsem** [comment] 2021-02-01 13:49
no i've changed it already i copied my packages in the home folder at the start of do_chroot like the qemu-aarch64 static and changed the pacman command, but so updating the bootimg only is enough?

**Comment by provokateurin** [comment] 2021-02-01 13:51
If you also updated [this](https://github.com/arch-beryllium/build/blob/main/build.sh#L244) function it should work.

**Comment by jedugsem** [comment] 2021-02-01 14:06
nice that was what i meant

**Comment by jedugsem** [comment] 2021-02-28 09:28
Hello,
I tried to build arch again and i get a error because of some currupted packages:
(503/503) checking package integrity               [############] 100%
:: File /var/cache/pacman/pkg/alsa-ucm-beryllium-0.2-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
:: File /var/cache/pacman/pkg/qrtr-git-r93.9dc7a88-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
:: File /var/cache/pacman/pkg/tqftpserv-git-r13.44af146-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
:: File /var/cache/pacman/pkg/rmtfs-git-r55.1cc12d3-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
:: File /var/cache/pacman/pkg/pd-mapper-git-r13.d7fe25f-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

**Comment by provokateurin** [comment] 2021-02-28 09:51
Sounds like I uploaded corrupt packages. Btw I also updated a few of the tools and packages so you should also update those.

**Comment by provokateurin** [comment] 2021-02-28 10:00
I know what the problem is. Please delete the `mirror/beryllium` folder in the mirror tool and start it. After that the issue should be gone. (Also `git pull` before doing that as some sources have changed too. Now that I think of it you should also delete the `mirror/plasma-mobile` folder)

**Comment by jedugsem** [comment] 2021-02-28 11:43
thanks biggest problem fixed but i get this output this time:
:: File /var/cache/pacman/pkg/firmware-xiaomi-beryllium-git-r7.g5dff7ac-4-any.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n]
error: failed to commit transaction

**Comment by jedugsem** [comment] 2021-02-28 11:44
i think the one uploaded is corrupt

**Comment by jedugsem** [comment] 2021-02-28 11:44
i deleted local beryllium mirror

**Comment by provokateurin** [comment] 2021-02-28 12:49
I tried it and I have no problems with it. It has to be your mirrored version that is corrupt. You can simply delete the file and start the tool. (Maybe I could add checksum checking to the tool so things like this won't happen)

**Comment by jedugsem** [comment] 2021-02-28 14:39
building worked :) and i think atm there is no need for you to work on the checksum thing

**Comment by jedugsem** [comment] 2021-02-28 14:40
but plasma-mobile-apps isn't buildable because index(mauikit file thing) Package is missing

**Comment by provokateurin** [comment] 2021-02-28 19:15
Ah yes I can fix that quickly

**Comment by provokateurin** [comment] 2021-02-28 19:27
Pushed. Should work now

**Comment by provokateurin** [comment] 2021-03-01 15:37
I went ahead and created a new mirror tool completely written in bash which also does check the checksums. The instructions are in the updated readme

**Comment by provokateurin** [comment] 2021-03-29 06:51
Venji finished rebased/rewrote the ebbg driver. You might want to try it and confirm it's working. After it's merged to the main branch I'll build the kernel package in a way that works for both panels. Only need to come up with a good plan on how to do it properly.

**Comment by provokateurin** [comment] 2021-03-29 08:18
I built the kernel package and updated the build script. You can try it now

**Comment by provokateurin** [comment] 2021-05-23 17:01
Btw there is a group now if you are interested. The group can be reached under the bridged rooms https://matrix.to/#/#arch-beryllium:matrix.org and https://t.me/arch_beryllium.

**Closed as completed by provokateurin** 2021-05-23 17:01 UTC
